export const movies = [
  { "id":1, "category":"thriller", "description":"Ψυχολογικό θρίλερ", "title":"Vertigo", "year":"1958", "director":"Alfred Hitchcock",
    "actors":"James Stewart, Kim Novak", 
    "url":"assets/img/vertigo.jpg" },
  { "id":2, "category":"comedy", "description":"Κωμωδία φαντασίας", "title":"Midnight in Paris", "year":"2011", "director":"Woody Allen",
    "actors":"Kathy Bates, Adrien Brody, Carla Bruni, Marion Cotillard", 
    "url":"assets/img/midnight-in-paris.jpg" },
  { "id":3, "category":"scifi", "description":"Νεο-noir επιστημονικής φαντασίας", "title":"Blade Runner", "year":"1982", "director":"Ridley Scott",
    "actors":"Harrison Ford, Rutger Hauer, Sean Young", 
    "url":"assets/img/blade-runner.jpg" },
  { "id":4, "category":"comedy", "description":"Κωμωδία", "title":"Life of Brian", "year":"1979", "director":"Terry Jones",
    "actors":"Graham Chapman, John Cleese, Terry Gilliam, Eric Idle, Terry Jones, Michael Palin", 
    "url":"assets/img/life-of-brian.jpg" },
  { "id":5, "category":"action", "description":"Περιπέτεια επιστημονικής φαντασίας", "title":"RoboCop", "year":"1987", "director":"Paul Verhoeven",
    "actors":"Peter Weller, Nancy Allen", 
    "url":"assets/img/robocop.jpg" },
  { "id":6, "category":"romance", "description":"Αισθηματική κομεντί", "title":"When Harry Met Sally", "year":"1989", "director":"Rob Reiner",
    "actors":"Billy Crystal, Meg Ryan", 
    "url":"assets/img/when-harry.jpg" },
  { "id":7, "category":"horror", "description":"Τρόμου", "title":"The Exorcist", "year":"1973", "director":"William Friedkin",
    "actors":"Ellen Burstyn, Max von Sydow, Lee J. Cobb", 
    "url":"assets/img/exorcist.jpg" },
  { "id":8, "category":"comedy", "description":"Κωμωδία", "title":"Groundhog Day", "year":"1993", "director":"Harold Ramis",
    "actors":"Bill Murray, Andie MacDowell, Chris Elliott", 
    "url":"assets/img/groundhog-day.jpg" },
  { "id":9, "category":"drama", "description":"Δραματική", "title":"Leaving Las Vegas", "year":"1995", "director":"Mike Figgis",
    "actors":"Nicolas Cage, Elisabeth Shue, Julian Sands", 
    "url":"assets/img/leaving-las-vegas.jpg" },
  { "id":10, "category":"crime", "description":"Αστυνομική", "title":"Get Carter", "year":"1971", "director":"Mike Hodges",
    "actors":"Michael Caine, Ian Hendry, John Osborne, Britt Ekland", 
    "url":"assets/img/get-carter.jpg" },
  { "id":11, "category":"action", "description":"Κατασκοπευτική περιπέτεια", "title":"From Russia with Love", "year":"1963", "director":"Terence Young",
    "actors":"Sean Connery, Pedro Armendáriz, Lotte Lenya, Robert Shaw, Bernard Lee, Daniela Bianchi", 
    "url":"assets/img/from-russia.jpg" },
  { "id":12, "category":"scifi", "description":"Περιπέτεια επιστημονικής φαντασίας", "title":"Matrix", "year":"1999", "director":"The Wachowskis",
    "actors":"Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss, Hugo Weaving, Joe Pantoliano", 
    "url":"assets/img/matrix.jpg" },
  { "id":13, "category":"drama", "description":"Ψυχολογικό δράμα", "title":"Persona", "year":"1966", "director":"Ingmar Bergman",
    "actors":"Bibi Andersson, Liv Ullmann", 
    "url":"assets/img/persona.jpg" },
  { "id":14, "category":"art", "description":"Σινεφίλ δράμα", "title":"Mirror", "year":"1975", "director":"Andrei Tarkovsky",
    "actors":"Margarita Terekhova, Ignat Daniltsev, Larisa Tarkovskaya, Alla Demidova, Anatoli Solonitsyn", 
    "url":"assets/img/mirror.jpg" },
  { "id":15, "category":"noir", "description":"Φιλμ noir αστυνομικό δράμα", "title":"Double Indemnity", "year":"1944", "director":"Billy Wilder",
    "actors":"Fred MacMurray, Barbara Stanwyck, Edward G. Robinson", 
    "url":"assets/img/double-indemnity.jpg" },
  { "id":16, "category":"drama", "description":"Φιλοσοφικό δράμα", "title":"The Turin Horse", "year":"2011", "director":"Béla Tarr",
    "actors":"János Derzsi, Erika Bók", 
    "url":"assets/img/turin-horse.jpg" },
  { "id":17, "category":"horror", "description":"Τρόμου", "title":"Let the Right One In", "year":"2008", "director":"Tomas Alfredson",
    "actors":"Kåre Hedebrant, Lina Leandersson, Per Ragnar, Ika Nord, Peter Carlberg", 
    "url":"assets/img/let-the-right.jpeg" },
  { "id":18, "category":"action", "description":"Περιπέτεια επιστημονικής φαντασίας", "title":"Inception", "year":"2010", "director":"Christopher Nolan",
    "actors":"Leonardo DiCaprio, Ken Watanabe, Joseph Gordon-Levitt, Marion Cotillard, Ellen Page, Tom Hardy", 
    "url":"assets/img/inception.jpg" },
  { "id":19, "category":"thriller", "description":"Νεο-noir ψυχολογικό θρίλερ", "title":"Taxi Driver", "year":"1976", "director":"Martin Scorsese",
    "actors":"Robert De Niro, Jodie Foster, Albert Brooks, Harvey Keitel", 
    "url":"assets/img/taxi-driver.jpg" },
  { "id":20, "category":"horror", "description":"Τρόμου", "title":"Psycho", "year":"1960", "director":"Alfred Hitchcock",
    "actors":"Anthony Perkins, Vera Miles, John Gavin, Martin Balsam, John McIntire, Janet Leigh", 
    "url":"assets/img/psycho.jpg" },
  { "id":21, "category":"thriller", "description":"Θρίλερ", "title":"North by Northwest", "year":"1959", "director":"Alfred Hitchcock",
    "actors":"Cary Grant, Eva Marie Saint, James Mason", 
    "url":"assets/img/north-by-northwest.jpg" },
  { "id":22, "category":"thriller", "description":"Νεο-noir θρίλερ μυστηρίου", "title":"Mulholland Drive", "year":"2001", "director":"David Lynch",
    "actors":"Naomi Watts, Laura Elena Harring, Justin Theroux, Ann Miller, Robert Forster", 
    "url":"assets/img/mulholland-drive.jpg" },
  { "id":23, "category":"drama", "description":"Δραματική κομεντί", "title":"The Breakfast Club", "year":"1985", "director":"John Hughes",
    "actors":"Emilio Estevez, Paul Gleason, Anthony Michael Hall, Judd Nelson, Molly Ringwald, Ally Sheedy", 
    "url":"assets/img/breakfast-club.jpg" },
  { "id":24, "category":"crime", "description":"Αστυνομική", "title":"Carlito's Way", "year":"1993", "director":"Brian De Palma",
    "actors":"Al Pacino, Sean Penn, Penelope Ann Miller", 
    "url":"assets/img/carlito.jpg" }
]
